'use client';
import {use,useCallback,useEffect,useRef,useState} from 'react'; import Link from 'next/link'; import {useRouter} from 'next/navigation'; import {apiUrl,getJSON,getWebSocketUrl,postJSON} from '../../../lib/api'; import {cents,teamName,clockTime} from '../../../lib/display'; import {LatencyMetrics,LatencySample,summarizeLatency} from '../../../lib/latency';
type State={session:any;markets:any[];events:any[];latest_calibration:any;quotes:Record<string,any>;score:any;health:any;recorder:any;preflight:any};
type Human={id:string;event_group_id:string;event_type:string;team?:string;device_wall_ts_ms:number;device_perf_ts_ms?:number;pointerdown_perf_ts_ms?:number;server_receive_ts_ns?:number;target_event_id?:string;detail?:Record<string,unknown>};
type PendingState={primary:Human;assessment?:string;varChecked:boolean;resolution?:string;voided:boolean;pending:boolean};
const eventLabels:Record<string,string>={DANGER:'危险进攻',SHOT:'射门',BALL_IN_NET:'进球事件',GOAL_ASSESSMENT:'进球初判',GOAL_CONFIRMED:'进球有效',GOAL_CANCELLED:'进球取消',PENALTY_EVENT:'点球事件',PENALTY_ASSESSMENT:'点球初判',PENALTY_CONFIRMED:'确认点球',PENALTY_CANCELLED:'取消点球',RED_CARD_EVENT:'红牌事件',RED_CARD_ASSESSMENT:'红牌初判',RED_CARD_CONFIRMED:'确认红牌',RED_CARD_CANCELLED:'取消 / 改判',VAR_CHECK:'VAR',EVENT_VOIDED:'误触作废'};
const primaryTypes=new Set(['BALL_IN_NET','PENALTY_EVENT','RED_CARD_EVENT']);
const assessmentTypes:Record<string,string>={BALL_IN_NET:'GOAL_ASSESSMENT',PENALTY_EVENT:'PENALTY_ASSESSMENT',RED_CARD_EVENT:'RED_CARD_ASSESSMENT'};
const resolutionTypes:Record<string,Set<string>>={BALL_IN_NET:new Set(['GOAL_CONFIRMED','GOAL_CANCELLED']),PENALTY_EVENT:new Set(['PENALTY_CONFIRMED','PENALTY_CANCELLED']),RED_CARD_EVENT:new Set(['RED_CARD_CONFIRMED','RED_CARD_CANCELLED'])};
function buildPendingEventState(events:Human[]):PendingState[]{const groups=new Map<string,Human[]>();for(const event of events){const list=groups.get(event.event_group_id)||[];list.push(event);groups.set(event.event_group_id,list)}const states:PendingState[]=[];for(const groupEvents of groups.values()){groupEvents.sort((a,b)=>(a.server_receive_ts_ns||a.device_wall_ts_ms*1e6)-(b.server_receive_ts_ns||b.device_wall_ts_ms*1e6));const primary=groupEvents.find(e=>primaryTypes.has(e.event_type));if(!primary)continue;const assessment=[...groupEvents].reverse().find(e=>e.event_type===assessmentTypes[primary.event_type])?.detail?.assessment as string|undefined;const resolution=groupEvents.find(e=>resolutionTypes[primary.event_type].has(e.event_type))?.event_type;const voided=groupEvents.some(e=>e.event_type==='EVENT_VOIDED'&&e.target_event_id===primary.id);const varChecked=groupEvents.some(e=>e.event_type==='VAR_CHECK'&&e.detail?.parent_event_id===primary.id);states.push({primary,assessment,varChecked,resolution,voided,pending:!resolution&&!voided})}return states.sort((a,b)=>(b.primary.server_receive_ts_ns||b.primary.device_wall_ts_ms*1e6)-(a.primary.server_receive_ts_ns||a.primary.device_wall_ts_ms*1e6))}
export default function Match({params}:{params:Promise<{id:string}>}){const {id}=use(params),[s,setS]=useState<State|null>(null),[quotes,setQuotes]=useState<Record<string,any>>({}),[optimistic,setOptimistic]=useState<Human[]>([]),[eventError,setEventError]=useState(''),[browserWs,setBrowserWs]=useState(false),[confirmStop,setConfirmStop]=useState(false),[latencyRunning,setLatencyRunning]=useState(false),[latencyProgress,setLatencyProgress]=useState(0),[latencyMetrics,setLatencyMetrics]=useState<LatencyMetrics|null>(null),[latencyError,setLatencyError]=useState(''),last=useRef<{id:string;group:string}|undefined>(undefined),pointerdowns=useRef<Record<string,number>>({}),router=useRouter();
const load=useCallback(()=>getJSON(`/api/sessions/${id}/state`).then((x:State)=>{setS(x);setQuotes(q=>({...q,...x.quotes}));const saved=new Set(x.events.map(e=>e.id));setOptimistic(items=>items.filter(e=>!saved.has(e.id)))}),[id]);
useEffect(()=>{let alive=true;postJSON(`/api/sessions/${id}/focus`,{}).then(()=>{if(alive)return load()}).catch(()=>load());const poll=window.setInterval(()=>{if(alive)load()},2000);const ws=new WebSocket(getWebSocketUrl());ws.onopen=()=>{setBrowserWs(true);ws.send('ui')};ws.onclose=()=>setBrowserWs(false);ws.onerror=()=>setBrowserWs(false);ws.onmessage=e=>{const d=JSON.parse(e.data);if(d.type==='market_batch')setQuotes(q=>{const n={...q};d.items.forEach((x:any)=>n[x.ticker||x.market_ticker]=x);return n});if(['markets_added','human_event','score'].includes(d.type))load()};return()=>{alive=false;window.clearInterval(poll);ws.close()}},[load,id]);
useEffect(()=>{const mark=(event:MouseEvent)=>{const target=event.target as HTMLElement;if(target.closest('a[href="/"]'))sessionStorage.setItem('csl-list-navigation-start',String(performance.now()))};document.addEventListener('click',mark);return()=>document.removeEventListener('click',mark)},[]);
if(!s)return <main className="page">Loading…</main>;const current=s,h=s.health,r=s.recorder,groups=s.markets.reduce((a:any,m:any)=>{(a[m.group_name]??=[]).push(m);return a},{}),families=h.market_family_counts||{};
const persistedIds=new Set(s.events.map((e:any)=>e.id)),allEvents=[...s.events,...optimistic.filter(e=>!persistedIds.has(e.id))].sort((a:any,b:any)=>(a.server_receive_ts_ns||a.device_wall_ts_ms*1e6)-(b.server_receive_ts_ns||b.device_wall_ts_ms*1e6));
const pendingStates=buildPendingEventState(allEvents),pending=pendingStates.filter(x=>x.pending),voidedIds=new Set(pendingStates.filter(x=>x.voided).map(x=>x.primary.id)),recentEvents=allEvents.filter((e:any)=>!voidedIds.has(e.id)).slice(-6).reverse();
const shownLatency=latencyMetrics||(s.latest_calibration?{rtt_last_ms:s.latest_calibration.rtt_last_ms,rtt_p50_ms:s.latest_calibration.rtt_p50_ms,rtt_p95_ms:s.latest_calibration.rtt_p95_ms,rtt_p99_ms:s.latest_calibration.rtt_p99_ms,estimated_one_way_ms:s.latest_calibration.estimated_one_way_ms,offset_ms:s.latest_calibration.offset_ms,jitter_ms:s.latest_calibration.jitter_ms}:null);
function capturePointer(key:string){pointerdowns.current[key]=performance.now()}
function record(type:string,team?:string,group?:string,detail:any={},trackAsLast=true,pointerKey?:string){const deviceWall=Date.now(),devicePerf=performance.now(),capturedPointer=pointerKey?pointerdowns.current[pointerKey]:undefined,pointerdownPerf=capturedPointer!=null&&capturedPointer<=devicePerf&&devicePerf-capturedPointer<2000?capturedPointer:undefined;if(pointerKey)delete pointerdowns.current[pointerKey];const eventId=crypto.randomUUID(),eventGroup=group||crypto.randomUUID();const local:Human={id:eventId,event_group_id:eventGroup,event_type:type,team,device_wall_ts_ms:deviceWall,device_perf_ts_ms:devicePerf,pointerdown_perf_ts_ms:pointerdownPerf,target_event_id:detail.target_event_id,detail};if(trackAsLast)last.current={id:eventId,group:eventGroup};setOptimistic(items=>[...items,local]);setEventError('');void postJSON(`/api/sessions/${id}/events`,{event_id:eventId,event_group_id:eventGroup,event_type:type,team,device_wall_ts_ms:deviceWall,device_perf_ts_ms:devicePerf,pointerdown_perf_ts_ms:pointerdownPerf,calibration_id:current.latest_calibration?.id||null,score_at_click:current.score,kalshi_match_clock_at_click:current.score.clock,target_event_id:detail.target_event_id,detail}).then((result:any)=>{if(result.duplicate)setOptimistic(items=>items.filter(e=>e.id!==eventId));return load()}).catch(()=>setEventError('事件发送失败，请立即重试；本地时间已保留在当前页面。'));return {eventId,eventGroup}}
function primary(type:string,team:string,key:string){record(type,team,undefined,{},true,key)}
function follow(e:Human,type:string,detail:any={}){record(type,e.team,e.event_group_id,{...detail,parent_event_id:e.id},false)}
function voidEvent(e:Human){record('EVENT_VOIDED',undefined,e.event_group_id,{target_event_id:e.id,reason:'MISTAP'},false)}
async function stopRecording(){await postJSON(`/api/sessions/${id}/end`,{});router.push('/')}
async function runLatencyTest(){setLatencyRunning(true);setLatencyProgress(0);setLatencyError('');try{const calibrationId=crypto.randomUUID(),clientCreated=Date.now(),samples:LatencySample[]=[];for(let sequence=1;sequence<=20;sequence++){const clientSendEpoch=Date.now(),clientSendPerf=performance.now();const response=await fetch(apiUrl('/api/latency/ping'),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sequence}),cache:'no-store'});const clientReceivePerf=performance.now(),clientReceiveEpoch=Date.now();if(!response.ok)throw Error(await response.text());const pong=await response.json(),serverReceiveNs=String(pong.server_receive_ts_ns),serverSendNs=String(pong.server_send_ts_ns),serverReceiveMs=Number(serverReceiveNs)/1e6,serverSendMs=Number(serverSendNs)/1e6,serverProcessingMs=serverSendMs-serverReceiveMs,networkRtt=Math.max(0,(clientReceivePerf-clientSendPerf)-serverProcessingMs),offset=((serverReceiveMs-clientSendEpoch)+(serverSendMs-clientReceiveEpoch))/2;samples.push({sequence,client_send_epoch_ms:clientSendEpoch,client_send_performance_ms:clientSendPerf,server_receive_ts_ns:serverReceiveNs,server_send_ts_ns:serverSendNs,client_receive_epoch_ms:clientReceiveEpoch,client_receive_performance_ms:clientReceivePerf,network_rtt_ms:networkRtt,clock_offset_ms:offset});setLatencyProgress(sequence)}const metrics=summarizeLatency(samples);await postJSON(`/api/sessions/${id}/calibrations`,{calibration_id:calibrationId,client_created_ts_ms:clientCreated,samples,...metrics});setLatencyMetrics(metrics);await load()}catch(error){setLatencyError(error instanceof Error?error.message:'Latency test failed')}finally{setLatencyRunning(false)}}
return <main className="page"><Link className="back" href="/">← 比赛列表</Link><div className={`mode-banner ${s.session.session_type==='MATCH_DAY'?'match-day':''}`}>{s.session.session_type}</div><div className="teams"><span>{teamName(s.session.home_team)}</span><span>{teamName(s.session.away_team)}</span></div><div className="score">{s.score.home} : {s.score.away}</div><p className="muted center">Score {s.score.source}</p>
<div className="status"><span className={h.connected?'dot':'bad'}>● KALSHI {h.connected?'CONNECTED':'DOWN'}</span><span className={browserWs?'dot':'bad'}>● UI {browserWs?'CONNECTED':'DOWN'}</span><span className={r.raw_recorder?'dot':'bad'}>● RECORDER {r.raw_recorder?'ON':'WAITING'}</span><span>Last Kalshi msg {h.last_ws_message_age_ms==null?'—':`${(h.last_ws_message_age_ms/1000).toFixed(1)}s ago`}</span></div>
<section className="card live-data"><h2>LIVE DATA</h2><div className="kv"><span>Focus</span><b>{teamName(s.session.home_team)} vs {teamName(s.session.away_team)}</b><span>Mode</span><b>{s.session.session_type}</b><span>Session</span><b>{s.session.ended_at?'STOPPED':'ACTIVE'}</b><span>WS Markets</span><b>{h.subscribed_market_count}</b><span>Other Games</span><b className={h.other_game_markets===0?'ok':'bad'}>{h.other_game_markets}</b></div><div className="family"><span>GAME <b>{families.GAME||0}</b></span><span>BTTS <b>{families.BTTS||0}</b></span><span>TOTAL <b>{families.TOTAL||0}</b></span><span>SPREAD <b>{families.SPREAD||0}</b></span></div><div className="kv"><span>Market Discovery</span><b className={h.discovery_status==='ACTIVE'?'ok':'bad'}>{h.discovery_status}</b><span>Last Discovery Scan</span><b>{h.last_discovery_scan_age_ms==null?'waiting':`${(h.last_discovery_scan_age_ms/1000).toFixed(1)}s ago`}</b></div></section>
{Object.entries(groups).map(([g,ms]:any)=><section className="card" key={g}><h2>{g}</h2>{ms.map((m:any)=>{const q=quotes[m.ticker]||{};return <div className="market" key={m.ticker}><span>{m.title}</span><span className="four-quote"><small>YES</small><b>{cents(q.yes_bid??q.yes_bid_dollars)} / {cents(q.yes_ask??q.yes_ask_dollars)}</b><small>NO</small><b>{cents(q.no_bid??q.no_bid_dollars)} / {cents(q.no_ask??q.no_ask_dollars)}</b></span></div>})}</section>)}
<div className="event-columns"><b>{teamName(s.session.home_team)}</b><b>{teamName(s.session.away_team)}</b></div>
<section className="event-grid"><button className="button event threat" onPointerDown={()=>capturePointer('DANGER-HOME')} onClick={()=>primary('DANGER','HOME','DANGER-HOME')}>{teamName(s.session.home_team)}<span>DANGER</span></button><button className="button event threat" onPointerDown={()=>capturePointer('DANGER-AWAY')} onClick={()=>primary('DANGER','AWAY','DANGER-AWAY')}>{teamName(s.session.away_team)}<span>DANGER</span></button><button className="button event shot" onPointerDown={()=>capturePointer('SHOT-HOME')} onClick={()=>primary('SHOT','HOME','SHOT-HOME')}>{teamName(s.session.home_team)}<span>SHOT</span></button><button className="button event shot" onPointerDown={()=>capturePointer('SHOT-AWAY')} onClick={()=>primary('SHOT','AWAY','SHOT-AWAY')}>{teamName(s.session.away_team)}<span>SHOT</span></button><button className="button event goal" onPointerDown={()=>capturePointer('GOAL-HOME')} onClick={()=>primary('BALL_IN_NET','HOME','GOAL-HOME')}>{teamName(s.session.home_team)}<span>GOAL</span></button><button className="button event goal" onPointerDown={()=>capturePointer('GOAL-AWAY')} onClick={()=>primary('BALL_IN_NET','AWAY','GOAL-AWAY')}>{teamName(s.session.away_team)}<span>GOAL</span></button><button className="button event penalty" onPointerDown={()=>capturePointer('PENALTY-HOME')} onClick={()=>primary('PENALTY_EVENT','HOME','PENALTY-HOME')}>{teamName(s.session.home_team)}<span>PENALTY</span></button><button className="button event penalty" onPointerDown={()=>capturePointer('PENALTY-AWAY')} onClick={()=>primary('PENALTY_EVENT','AWAY','PENALTY-AWAY')}>{teamName(s.session.away_team)}<span>PENALTY</span></button><button className="button event red" onPointerDown={()=>capturePointer('RED-HOME')} onClick={()=>primary('RED_CARD_EVENT','HOME','RED-HOME')}>{teamName(s.session.home_team)}<span>RED</span></button><button className="button event red" onPointerDown={()=>capturePointer('RED-AWAY')} onClick={()=>primary('RED_CARD_EVENT','AWAY','RED-AWAY')}>{teamName(s.session.away_team)}<span>RED</span></button></section>
<button className="button global-var" onPointerDown={()=>capturePointer('VAR-GLOBAL')} onClick={()=>record('VAR_CHECK',undefined,undefined,{},true,'VAR-GLOBAL')}>VAR</button>
<section className="pending-events"><h2>待确认事件</h2>{pending.length?pending.map((state:PendingState)=>{const e=state.primary,assessmentText=state.assessment==='LIKELY_VALID'?(e.event_type==='BALL_IN_NET'?'明显有效':'明显成立'):state.assessment==='OFFSIDE_OR_FOUL_RISK'?'存在越位 / 犯规风险':state.assessment==='DISPUTED'?'存在争议':'';return <article className="pending-event" key={e.id}><div><time>{new Date(e.device_wall_ts_ms).toLocaleTimeString()}</time><b>{teamName(e.team==='HOME'?s.session.home_team:s.session.away_team)} · {eventLabels[e.event_type]}</b></div>{assessmentText&&<p className="pending-state">初判：{assessmentText}</p>}{state.varChecked&&<p className="pending-state">VAR 已记录</p>}<div className="pending-actions">{!state.assessment&&e.event_type==='BALL_IN_NET'&&<><button onClick={()=>follow(e,'GOAL_ASSESSMENT',{assessment:'LIKELY_VALID'})}>明显有效</button><button onClick={()=>follow(e,'GOAL_ASSESSMENT',{assessment:'OFFSIDE_OR_FOUL_RISK'})}>存在越位 / 犯规风险</button></>}{!state.assessment&&e.event_type==='PENALTY_EVENT'&&<><button onClick={()=>follow(e,'PENALTY_ASSESSMENT',{assessment:'LIKELY_VALID'})}>明显成立</button><button onClick={()=>follow(e,'PENALTY_ASSESSMENT',{assessment:'DISPUTED'})}>存在争议</button></>}{!state.assessment&&e.event_type==='RED_CARD_EVENT'&&<><button onClick={()=>follow(e,'RED_CARD_ASSESSMENT',{assessment:'LIKELY_VALID'})}>明显成立</button><button onClick={()=>follow(e,'RED_CARD_ASSESSMENT',{assessment:'DISPUTED'})}>存在争议</button></>}{!state.varChecked&&<button onClick={()=>follow(e,'VAR_CHECK')}>VAR</button>}{e.event_type==='BALL_IN_NET'&&<><button onClick={()=>follow(e,'GOAL_CONFIRMED')}>进球有效</button><button onClick={()=>follow(e,'GOAL_CANCELLED')}>进球取消</button></>}{e.event_type==='PENALTY_EVENT'&&<><button onClick={()=>follow(e,'PENALTY_CONFIRMED')}>点球确认</button><button onClick={()=>follow(e,'PENALTY_CANCELLED')}>点球取消</button></>}{e.event_type==='RED_CARD_EVENT'&&<><button onClick={()=>follow(e,'RED_CARD_CONFIRMED')}>红牌确认</button><button onClick={()=>follow(e,'RED_CARD_CANCELLED')}>取消 / 改判</button></>}<button className="void" onClick={()=>voidEvent(e)}>误触作废</button></div></article>}):<p className="muted">没有待确认事件</p>}</section>
<div className="toolbar footer-actions"><button className="button danger" onClick={()=>last.current&&record('EVENT_VOIDED',undefined,last.current.group,{target_event_id:last.current.id,reason:'MISTAP'},false)}>误触 / 撤销上一条</button><Link className="button" href={`/match/${id}/data`}>DATA</Link><Link className="button" href={`/replay/${id}`}>回放记录</Link></div><button className="button stop-recording" onClick={()=>setConfirmStop(true)}>STOP RECORDING</button>
<section className="card latency-test"><h2>PHONE ↔ AWS LATENCY</h2><button className="button" disabled={latencyRunning} onClick={runLatencyTest}>{latencyRunning?`TESTING ${latencyProgress}/20`:'RUN LATENCY TEST'}</button>{shownLatency&&<div className="kv latency-results"><span>RTT last</span><b>{shownLatency.rtt_last_ms.toFixed(1)} ms</b><span>RTT p50</span><b>{shownLatency.rtt_p50_ms.toFixed(1)} ms</b><span>RTT p95</span><b>{shownLatency.rtt_p95_ms.toFixed(1)} ms</b><span>RTT p99</span><b>{shownLatency.rtt_p99_ms.toFixed(1)} ms</b><span>Estimated one-way</span><b>~{shownLatency.estimated_one_way_ms.toFixed(1)} ms</b><span>Clock offset</span><b>{shownLatency.offset_ms.toFixed(1)} ms</b><span>Jitter</span><b>{shownLatency.jitter_ms.toFixed(1)} ms</b></div>}{latencyError&&<p className="bad">{latencyError}</p>}<p className="muted">20 次独立 ping；不写 Human Event，不触发 Kalshi。One-way 和 clock offset 为估算值。</p></section>
<section className="recent"><h2>RECENT HUMAN EVENTS</h2>{recentEvents.length?recentEvents.map((e:any)=><div className="event-row" key={e.id}><span>{e.server_receive_ts_ns?clockTime(e.server_receive_ts_ns):new Date(e.device_wall_ts_ms).toLocaleTimeString()}</span><b>{e.team?teamName(e.team==='HOME'?s.session.home_team:s.session.away_team)+' · ':''}{eventLabels[e.event_type]||e.event_type}</b></div>):<p className="muted">还没有现场事件</p>}{eventError&&<p className="bad">{eventError}</p>}</section>
{confirmStop&&<div className="sheet"><h2>STOP RECORDING</h2><p>停止记录当前比赛？</p><div className="match">{teamName(s.session.home_team)} vs {teamName(s.session.away_team)}</div><p className="muted">停止后：<br/>- 当前 Session 将变为 STOPPED<br/>- 已记录数据不会删除<br/>- Kalshi Focus subscriptions 将停止<br/>- 可以从 Session History 查看数据</p><button className="button" onClick={()=>setConfirmStop(false)}>取消</button><button className="button danger" onClick={stopRecording}>停止记录</button></div>}</main>}
