'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ApiError,getJSON,postJSON} from '../../../../lib/api';
import {createNetworkTestEvent,sampleClock,type Calibration,type NetworkTestEvent} from '../../../../lib/network-test';
import {browserNetworkTestStorage,NetworkTestOutbox} from '../../../../lib/network-test-outbox';
import {LogoutButton} from '../../../components/logout-button';

type Run={test_run_id:string;label:string;status:string;started_at:string;max_events:number};
type Boot={active_run:Run|null;test_only:boolean;limits:{per_minute:number;max_events:number}};
type Ack={event_id:string;duplicate:boolean;expired:boolean;server_request_entry_ts_ns:string;server_validation_complete_ts_ns:string;server_ack_ready_ts_ns:string;client_rtt_ms:number;queue_ms:number};

export default function NetworkTestPage(){
  const [boot,setBoot]=useState<Boot|null>(null),[online,setOnline]=useState(true),[pending,setPending]=useState(0),[calibration,setCalibration]=useState<Calibration|null>(null),[calibrating,setCalibrating]=useState(false),[vpn,setVpn]=useState<boolean|null>(null),[lastAck,setLastAck]=useState<Ack|null>(null),[error,setError]=useState(''),[running,setRunning]=useState('');
  const outbox=useRef<NetworkTestOutbox|null>(null),pointer=useRef<{perf:number;wall:number}|null>(null),timers=useRef<number[]>([]),lastDelivered=useRef<{runId:string;event:NetworkTestEvent}|null>(null);
  const load=useCallback(()=>getJSON('/api/network-tests/operator/bootstrap').then(setBoot).catch(e=>{if(e instanceof ApiError&&e.status===401)location.assign('/login');else setError('NETWORK TEST status unavailable')}),[]);
  useEffect(()=>{void load();const poll=setInterval(load,3000);const onlineHandler=()=>{setOnline(true);outbox.current?.retryAll()},offlineHandler=()=>setOnline(false),visible=()=>{if(document.visibilityState==='visible'){void load();outbox.current?.retryAll()}};setOnline(navigator.onLine);addEventListener('online',onlineHandler);addEventListener('offline',offlineHandler);document.addEventListener('visibilitychange',visible);return()=>{clearInterval(poll);removeEventListener('online',onlineHandler);removeEventListener('offline',offlineHandler);document.removeEventListener('visibilitychange',visible);timers.current.forEach(clearTimeout)}},[load]);
  useEffect(()=>{const manager=new NetworkTestOutbox({storage:browserNetworkTestStorage(),onChange:items=>setPending(items.length),send:async(runId,event)=>({...await postJSON(`/api/network-tests/operator/runs/${runId}/events`,event),client_fetch_start_perf_ms:event.fetch_start_perf_ms}),onDelivered:(item,response)=>{const ackPerf=performance.now(),ackWall=Date.now(),ui=()=>{const uiPerf=performance.now(),uiWall=Date.now();setLastAck({...response,client_rtt_ms:ackPerf-response.client_fetch_start_perf_ms,queue_ms:response.client_fetch_start_perf_ms-item.event.enqueue_perf_ms});void postJSON(`/api/network-tests/operator/runs/${item.runId}/events/${item.event.event_id}/client-ack`,{ack_perf_ms:ackPerf,ack_wall_ms:ackWall,ui_update_perf_ms:uiPerf,ui_update_wall_ms:uiWall})};lastDelivered.current={runId:item.runId,event:item.event};if(document.visibilityState==='visible')requestAnimationFrame(ui);else setTimeout(ui,0)}});outbox.current=manager;manager.start();return()=>{manager.stop();outbox.current=null}},[]);
  const run=boot?.active_run;
  async function calibrate(){if(!run)return;setCalibrating(true);setError('');try{const next=await sampleClock(run.test_run_id,postJSON,10);await postJSON(`/api/network-tests/operator/runs/${run.test_run_id}/calibrations`,next);setCalibration(next)}catch{setError('Clock calibration failed. Check VPN/network and retry.')}finally{setCalibrating(false)}}
  function capture(){pointer.current={perf:performance.now(),wall:Date.now()}}
  function enqueue(scenario:NetworkTestEvent['scenario']='MANUAL',reuse?:NetworkTestEvent){if(!run){setError('No ADMIN-authorized NETWORK TEST is active.');return}const event=reuse?{...reuse,scenario}:{...createNetworkTestEvent(scenario,vpn,pointer.current||undefined),calibration_id:calibration?.calibration_id||null};pointer.current=null;outbox.current?.enqueue(run.test_run_id,event);void outbox.current?.retry(event.event_id)}
  function schedule(name:string,count:number,intervalMs:number,scenario:NetworkTestEvent['scenario']){if(!run||running)return;setRunning(name);for(let index=0;index<count;index++)timers.current.push(window.setTimeout(()=>{enqueue(scenario);if(index===count-1)setRunning('')},index*intervalMs))}
  function stop(){timers.current.forEach(clearTimeout);timers.current=[];setRunning('')}
  function duplicate(){const last=lastDelivered.current;if(!last){setError('Send one test event before duplicate verification.');return}enqueue('DUPLICATE',{...last.event,scenario:'DUPLICATE'})}
  return <main className="signal-page network-test-page"><header className="signal-head"><div><small>CSLTradingLab · TEST ONLY</small><h1>NETWORK TEST</h1></div><LogoutButton/></header><Link className="back" href="/live/chongqing">← LIVE EVENT PAGE</Link>
    <div className="test-only-banner">TEST ONLY — NO MATCH · NO KALSHI · NO TRADING</div>
    <div className="connection-strip"><span className={online?'ok':'bad'}>● NETWORK {online?'ONLINE':'OFFLINE'}</span><span className={boot?'ok':'bad'}>● SERVER {boot?'CONNECTED':'DOWN'}</span><span className={run?'ok':'bad'}>● TEST {run?'AUTHORIZED':'INACTIVE'}</span></div>
    {run?<section className="ack-card"><b>{run.label}</b><p className="mono">{run.test_run_id}</p><p className="muted">Rate cap {boot?.limits.per_minute}/minute · Run cap {run.max_events}. VPN state is your confirmation, never inferred from IP.</p><div className="vpn-choice"><button className={vpn===true?'active':''} onClick={()=>setVpn(true)}>VPN CONFIRMED</button><button className={vpn===false?'active':''} onClick={()=>setVpn(false)}>NO VPN</button></div></section>:<section className="ack-card no-match"><b>NO ACTIVE NETWORK TEST</b><p className="muted">Ask ADMIN to create a test run. Test signals cannot be sent without explicit authorization.</p></section>}
    {error&&<p className="auth-error">{error}</p>}{pending>0&&<div className="queue-warning">{pending} TEST EVENT{pending>1?'S':''} IN OUTBOX</div>}
    <button className="button" disabled={!run||calibrating} onClick={calibrate}>{calibrating?'CALIBRATING 10 SAMPLES…':calibration?'RECALIBRATE CLOCK':'CALIBRATE CLOCK'}</button>{calibration&&<section className="ack-card"><h2>CLOCK CALIBRATION</h2><div className="ack-grid"><span>RTT P50</span><strong>{calibration.rtt_p50_ms.toFixed(1)} ms</strong><span>RTT P95</span><strong>{calibration.rtt_p95_ms.toFixed(1)} ms</strong><span>Offset estimate</span><strong>{calibration.offset_ms.toFixed(1)} ms</strong><span>Uncertainty</span><strong>±{calibration.uncertainty_ms.toFixed(1)} ms</strong></div></section>}
    <button className="signal-button network-test-trigger" disabled={!run} onPointerDown={capture} onClick={()=>enqueue('MANUAL')}>SEND TEST PULSE</button>
    <section className="scenario-grid"><button disabled={!run||!!running} onClick={()=>schedule('20 PULSES',20,500,'BURST_20')}>20 PULSES</button><button disabled={!run||!!running} onClick={()=>schedule('1 MINUTE',20,3000,'FIXED_1M')}>1 MIN · 3s</button><button disabled={!run||!!running} onClick={()=>schedule('5 MINUTES',100,3000,'SOAK_5M')}>5 MIN · 3s</button><button disabled={!lastAck} onClick={duplicate}>DUPLICATE LAST</button></section>{running&&<button className="button danger" onClick={stop}>STOP {running}</button>}
    <section className="ack-card"><h2>LAST ACK</h2>{lastAck?<div className="ack-grid"><span>Status</span><strong className={lastAck.expired?'bad':'ok'}>{lastAck.duplicate?'DEDUPLICATED':lastAck.expired?'EXPIRED / TEST ONLY':'ACK'}</strong><span>Full ACK RTT</span><strong>{lastAck.client_rtt_ms.toFixed(1)} ms</strong><span>Client queue</span><strong>{lastAck.queue_ms.toFixed(1)} ms</strong><span>Server processing</span><strong>{((Number(BigInt(lastAck.server_ack_ready_ts_ns)-BigInt(lastAck.server_request_entry_ts_ns)))/1e6).toFixed(2)} ms</strong><span>Event ID</span><strong>{lastAck.event_id}</strong></div>:<p className="muted">No test ACK yet.</p>}</section>
    <section className="ack-card"><h2>RECOVERY TEST</h2><p className="muted">Turn off network or switch VPN, press SEND TEST PULSE, then reconnect. The isolated outbox retains the original event ID and timestamps. Old recovered pulses are marked EXPIRED and can never enter a trading path.</p></section>
  </main>
}
