'use client';
import {useCallback,useEffect,useState} from 'react';
import {API,ApiError,getJSON,postJSON} from '../../lib/api';

type Run={test_run_id:string;label:string;status:string;started_at:string;max_events:number};
type Summary={run:Run;counts:Record<string,number>;rtt_ms:Record<string,number|null>;uplink_calibrated_ms:Record<string,number|string|null>;client_queue_ms:Record<string,number|null>;server_processing_ms:Record<string,number|null>;vpn:{confirmed_yes:number;confirmed_no:number;unknown:number;source:string};calibrations:number};
const metric=(value:number|null|undefined)=>value==null?'—':`${value.toFixed(1)} ms`;

export function NetworkTestAdmin(){
  const [runs,setRuns]=useState<Run[]>([]),[summary,setSummary]=useState<Summary|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const active=runs.find(x=>x.status==='ACTIVE')||null;
  const load=useCallback(async()=>{try{const data=await getJSON('/api/network-tests/admin/runs');setRuns(data.items);const target=data.items.find((x:Run)=>x.status==='ACTIVE')||data.items[0];setSummary(target?await getJSON(`/api/network-tests/admin/runs/${target.test_run_id}/summary`):null)}catch(e){if(!(e instanceof ApiError&&e.status===401))setError('NETWORK TEST monitor unavailable.')}},[]);
  useEffect(()=>{void load();const timer=setInterval(load,3000);return()=>clearInterval(timer)},[load]);
  async function create(){setBusy(true);setError('');try{await postJSON('/api/network-tests/admin/runs',{label:'Chongqing → AWS Ohio',notes:'Outline VPN path validation',max_events:600});await load()}catch(e){setError(e instanceof ApiError?`CREATE FAILED (${e.status})`:'CREATE FAILED')}finally{setBusy(false)}}
  async function end(){if(!active)return;setBusy(true);try{await postJSON(`/api/network-tests/admin/runs/${active.test_run_id}/end`,{});await load()}catch(e){setError(e instanceof ApiError?`END FAILED (${e.status})`:'END FAILED')}finally{setBusy(false)}}
  return <><h2>NETWORK TEST · TEST ONLY</h2><section className="card network-admin"><div className="test-only-banner">ISOLATED PATH — NEVER CONNECTED TO HUMAN EVENTS OR TRADING</div>{active?<><div className="match">{active.label}</div><p className="mono">{active.test_run_id}</p><div className="toolbar"><button className="button danger" disabled={busy} onClick={end}>END TEST</button></div></>:<><b>NO ACTIVE NETWORK TEST</b><p className="muted">Create an authorized run before the operator phone can send test pulses.</p><button className="button" disabled={busy} onClick={create}>{busy?'CREATING…':'CREATE NETWORK TEST'}</button></>}{error&&<p className="bad">{error}</p>}{summary&&<><div className="network-counts"><span>Sent<b>{summary.counts.sent}</b></span><span>Received<b>{summary.counts.received}</b></span><span>ACK<b>{summary.counts.ack}</b></span><span>Duplicate<b>{summary.counts.duplicate}</b></span><span>Failed<b>{summary.counts.failed}</b></span><span>Timeout<b>{summary.counts.timeout}</b></span></div><div className="kv"><span>RTT P50 / P95</span><b>{metric(summary.rtt_ms.p50)} / {metric(summary.rtt_ms.p95)}</b><span>RTT P99 / max</span><b>{metric(summary.rtt_ms.p99)} / {metric(summary.rtt_ms.max)}</b><span>Calibrated uplink P50</span><b>{metric(summary.uplink_calibrated_ms.p50 as number|null)}</b><span>Uplink uncertainty P95</span><b>±{metric(summary.uplink_calibrated_ms.uncertainty_p95 as number|null)}</b><span>Client queue P50 / P95</span><b>{metric(summary.client_queue_ms.p50)} / {metric(summary.client_queue_ms.p95)}</b><span>Server processing P50 / P95</span><b>{metric(summary.server_processing_ms.p50)} / {metric(summary.server_processing_ms.p95)}</b><span>VPN confirmation</span><b>YES {summary.vpn.confirmed_yes} · NO {summary.vpn.confirmed_no} · ? {summary.vpn.unknown}</b><span>Clock calibrations</span><b>{summary.calibrations}</b></div><p className="muted">Uplink uses NTP midpoint clock offset and reports its error bound. VPN is user-confirmed, never inferred from source IP.</p><div className="toolbar"><a className="button" href={`${API}/api/network-tests/admin/runs/${summary.run.test_run_id}/export.csv`}>EXPORT CSV</a><a className="button" href={`${API}/api/network-tests/admin/runs/${summary.run.test_run_id}/export.json`}>EXPORT JSON</a></div></>}</section></>;
}
