'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {API,ApiError,deleteJSON,getJSON,postJSON} from '../../lib/api';
import {teamName} from '../../lib/display';
import {LogoutButton} from '../components/logout-button';
import {NetworkTestAdmin} from './network-test-admin';
import './dashboard.css';

type Mode='TEST'|'MATCH_DAY';
type Match={event_ticker:string;home_team:string;away_team:string;status:string;markets:unknown[]};
type Session={id:string;event_ticker:string;home_team:string;away_team:string;session_type:string;status:string;started_at:string|null;ended_at:string|null;archived_at:string|null;human_events:number;kalshi_ws_messages:number;recorder_on:boolean;ws_markets:number};
const MATCH_CACHE='csl-last-known-matches',MODE_CACHE='csl-next-session-mode';
function cachedMatches():Match[]{if(typeof window==='undefined')return [];try{return JSON.parse(sessionStorage.getItem(MATCH_CACHE)||'[]')}catch{return []}}
function cachedMode():Mode{if(typeof window==='undefined')return 'TEST';return sessionStorage.getItem(MODE_CACHE)==='MATCH_DAY'?'MATCH_DAY':'TEST'}
function sessionTime(value:string|null){if(!value)return 'Now';const utc=/Z$|[+-]\d\d:\d\d$/.test(value)?value:`${value}Z`;return new Date(utc).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}

export default function Home(){
  const [items,setItems]=useState<Match[]>([]),[sessions,setSessions]=useState<Session[]>([]),[loading,setLoading]=useState(true),[authorized,setAuthorized]=useState(false),[entering,setEntering]=useState<string>(),[mode,setMode]=useState<Mode>('TEST'),[pending,setPending]=useState<Match|null>(null),[stopTarget,setStopTarget]=useState<Session|null>(null),[deleteTarget,setDeleteTarget]=useState<Session|null>(null),[deleteToken,setDeleteToken]=useState(''),[deleteError,setDeleteError]=useState(''),[actionError,setActionError]=useState(''),[showArchived,setShowArchived]=useState(false),[archivedCount,setArchivedCount]=useState(0),r=useRouter();
  const active=sessions.find(s=>s.status==='ACTIVE')||null,history=sessions.filter(s=>s.status!=='ACTIVE'&&!s.archived_at),archived=sessions.filter(s=>!!s.archived_at);
  const routeAuth=useCallback((e:unknown)=>{if(e instanceof ApiError)r.replace(e.status===401?'/login':'/forbidden')},[r]);
  const refreshSessions=useCallback(()=>getJSON(`/api/sessions${showArchived?'?include_archived=true':''}`).then((x:{items:Session[];archived_count:number})=>{setSessions(x.items);setArchivedCount(x.archived_count)}).catch(routeAuth),[routeAuth,showArchived]);
  useEffect(()=>{getJSON('/api/auth/me').then(x=>{if(!x.authenticated)r.replace('/login');else if(x.role!=='ADMIN')r.replace('/forbidden');else setAuthorized(true)}).catch(()=>r.replace('/login'))},[r]);
  useEffect(()=>{
    if(!authorized)return;
    const navigationStart=Number(sessionStorage.getItem('csl-list-navigation-start'))||performance.now(),cached=cachedMatches();setMode(cachedMode());
    if(cached.length){setItems(cached);setLoading(false);requestAnimationFrame(()=>{document.body.dataset.cacheVisibleMs=(performance.now()-navigationStart).toFixed(1)})}
    getJSON('/api/matches').then((next:Match[])=>{setItems(next);sessionStorage.setItem(MATCH_CACHE,JSON.stringify(next));document.body.dataset.refreshCompleteMs=(performance.now()-navigationStart).toFixed(1)}).catch(routeAuth).finally(()=>setLoading(false));
    refreshSessions();const timer=setInterval(refreshSessions,2000);return()=>clearInterval(timer)
  },[refreshSessions,authorized,routeAuth]);
  function selectMode(next:Mode){setMode(next);sessionStorage.setItem(MODE_CACHE,next)}
  function requestEnter(m:Match){if(entering)return;const same=active?.event_ticker===m.event_ticker;if((active&&!same)||(!active&&mode==='MATCH_DAY')){setPending(m);return}enter(m)}
  async function enter(m:Match){setEntering(m.event_ticker);try{const x=await postJSON('/api/sessions',{event_ticker:m.event_ticker,session_mode:mode});r.push(`/match/${x.session_id}`)}finally{setEntering(undefined)}}
  async function stopRecording(s:Session){await postJSON(`/api/sessions/${s.id}/end`,{});setStopTarget(null);await refreshSessions()}
  async function archiveSession(s:Session){setActionError('');try{await postJSON(`/api/sessions/${s.id}/archive`,{});await refreshSessions()}catch(e){setActionError(e instanceof ApiError?`ARCHIVE FAILED (${e.status}) — Data was not changed.`:'ARCHIVE FAILED — Data was not changed.')}}
  async function restoreSession(s:Session){setActionError('');try{await postJSON(`/api/sessions/${s.id}/restore`,{});await refreshSessions()}catch(e){setActionError(e instanceof ApiError?`RESTORE FAILED (${e.status}) — Data was not changed.`:'RESTORE FAILED — Data was not changed.')}}
  async function removeSession(){if(!deleteTarget)return;setDeleteError('');try{await deleteJSON(`/api/sessions/${deleteTarget.id}`,{confirmation:deleteToken});setDeleteTarget(null);setDeleteToken('');await refreshSessions()}catch(e){setDeleteError(e instanceof ApiError?`DELETE FAILED (${e.status}) — Data was not removed.`:'DELETE FAILED — Data was not removed.') }}
  if(!authorized)return <main className="page">Checking administrator authorization…</main>;
  return <main className="page"><header className="dashboard-head"><h1>CSL Trading Lab</h1><LogoutButton/></header><div className="mode"><button className={mode==='TEST'?'active':''} onClick={()=>selectMode('TEST')}>TEST</button><button className={mode==='MATCH_DAY'?'active':''} onClick={()=>selectMode('MATCH_DAY')}>MATCH DAY</button></div><p className="mode-summary">Next new Session: <b>{mode}</b></p>{active&&<p className="muted">Active Session remains <b>{active.session_type}</b>: {teamName(active.home_team)} vs {teamName(active.away_team)}</p>}
  <h2>UPCOMING / LIVE MATCHES</h2>{loading&&<p className="muted">Loading matches…</p>}{items.map(m=><section className="card compact" key={m.event_ticker}><div className="match">{teamName(m.home_team)} vs {teamName(m.away_team)}</div><p className="muted">{m.markets.length} Markets · {m.status}{active?.event_ticker===m.event_ticker?' · ACTIVE FOCUS':''}</p><button className="button" disabled={!!entering} onClick={()=>requestEnter(m)}>{entering===m.event_ticker?'CONNECTING…':active?.event_ticker===m.event_ticker?'RESUME MATCH':'ENTER MATCH'}</button></section>)}
  <h2>ACTIVE MATCH</h2>{active?<section className="card active-recording"><div className="match">{teamName(active.home_team)} vs {teamName(active.away_team)}</div><p><b>{active.session_type}</b></p><div className="kv"><span>Recorder</span><b className={active.recorder_on?'ok':'bad'}>{active.recorder_on?'ON':'WAITING'}</b><span>WS Markets</span><b>{active.ws_markets}</b><span>Human Events</span><b>{active.human_events}</b><span>WS Messages</span><b>{active.kalshi_ws_messages}</b></div><p className="muted">Session is still recording. Export is a snapshot up to now. 正式比赛建议停止记录后再导出。</p><div className="toolbar"><Link className="button" href={`/match/${active.id}`}>RESUME</Link><a className="button" href={`${API}/api/sessions/${active.id}/export`} download>DOWNLOAD ZIP</a><button className="button danger" onClick={()=>setStopTarget(active)}>STOP RECORDING</button></div></section>:<section className="card"><b>NO ACTIVE MATCH</b><p className="muted">Configure exact event and market tickers, then explicitly activate the match.</p></section>}
  <NetworkTestAdmin/>
  <h2>SESSION HISTORY</h2>{actionError&&<p className="bad">{actionError}</p>}<section className="history">{history.map(s=><article className="card history-row" key={s.id}><div><b>{teamName(s.home_team)} vs {teamName(s.away_team)}</b><p className="mono" title={s.id}>{s.id}</p></div><div className="history-meta"><b>{s.status}</b><span>{s.session_type}</span><span>{sessionTime(s.started_at)} – {sessionTime(s.ended_at)}</span><span>Human Events {s.human_events}</span><span>WS Messages {s.kalshi_ws_messages}</span></div><div className="history-actions"><Link className="button" href={`/match/${s.id}/data`}>VIEW DATA</Link><a className="button" href={`${API}/api/sessions/${s.id}/export`} download>DOWNLOAD ZIP</a><button className="button archive" onClick={()=>archiveSession(s)}>ARCHIVE</button></div></article>)}</section>
  <button className="button archive-toggle" onClick={()=>setShowArchived(value=>!value)}>{showArchived?'HIDE ARCHIVED':`SHOW ARCHIVED (${archivedCount})`}</button>{showArchived&&<section className="history archived-history">{archived.map(s=><article className="card history-row" key={s.id}><div><b>{teamName(s.home_team)} vs {teamName(s.away_team)}</b><p className="mono" title={s.id}>{s.id}</p></div><div className="history-meta"><b>ARCHIVED</b><span>{s.session_type}</span><span>Historical rows and raw files preserved</span></div><div className="history-actions"><Link className="button" href={`/match/${s.id}/data`}>VIEW DATA</Link><button className="button" onClick={()=>restoreSession(s)}>RESTORE</button><button className="button danger" onClick={()=>{setDeleteTarget(s);setDeleteToken('');setDeleteError('')}}>PERMANENT DELETE</button></div></article>)}</section>}
  {pending&&<div className="sheet"><h2>{active?'SWITCH FOCUS SESSION':'START MATCH DAY SESSION'}</h2>{active&&<><p>当前正在记录：</p><div className="match">{teamName(active.home_team)} vs {teamName(active.away_team)}</div><p className="muted">切换比赛将立即停止当前 Session。<br/>已记录数据不会删除。</p></>}<p>然后开始记录：</p><div className="match">{teamName(pending.home_team)} vs {teamName(pending.away_team)}</div><p className="muted">New Session mode: <b>{mode}</b></p><button className="button" onClick={()=>setPending(null)}>取消</button><button className="button danger" onClick={()=>{const match=pending;setPending(null);enter(match)}}>{active?'停止并切换':'开始记录'}</button></div>}
  {stopTarget&&<div className="sheet"><h2>STOP RECORDING</h2><p>停止记录当前比赛？</p><div className="match">{teamName(stopTarget.home_team)} vs {teamName(stopTarget.away_team)}</div><p className="muted">停止后：<br/>- 当前 Session 将变为 STOPPED<br/>- 已记录数据不会删除<br/>- Kalshi Focus subscriptions 将停止<br/>- 可以从 Session History 查看数据</p><button className="button" onClick={()=>setStopTarget(null)}>取消</button><button className="button danger" onClick={()=>stopRecording(stopTarget)}>停止记录</button></div>}
  {deleteTarget&&<div className="sheet"><h2>PERMANENT DELETE</h2><p>永久删除这个已归档的 {deleteTarget.session_type} Session？</p><div className="match">{teamName(deleteTarget.home_team)} vs {teamName(deleteTarget.away_team)}</div><p className="muted">影响范围：SQLite 中该 Session 的 Human Events、行情、订单簿、校准与系统事件，以及对应 raw NDJSON。此操作无法恢复；其他 Session 不受影响。服务端还要求最近 15 分钟内完成管理员二次验证。</p><label htmlFor="delete-confirm">请输入 <span className="mono">DELETE {deleteTarget.id}</span></label><input id="delete-confirm" className="confirm-input" value={deleteToken} onChange={e=>setDeleteToken(e.target.value)} autoComplete="off"/>{deleteError&&<p className="bad">{deleteError} {deleteError.includes('(403)')&&<Link href="/admin-verify">前往管理员二次验证</Link>}</p>}<button className="button" onClick={()=>setDeleteTarget(null)}>取消</button><button className="button danger" disabled={deleteToken!==`DELETE ${deleteTarget.id}`} onClick={removeSession}>永久删除</button></div>}</main>
}
